name: Build_and_redeploy_with_N2R

concurrency:
  group: notebook2rest-pipeline
  cancel-in-progress: true

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

env:
  AWS_REGION: eu-north-1
  EKS_CLUSTER_NAME: notebook2rest_cluster
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REPOSITORY: notebook2rest/api
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_number }}
  NOTEBOOK_REPOSITORY_NAME: vl-laserfarm
  NOTEBOOK_REPOSITORY_URL: https://github.com/devops-notebook2rest/vl-laserfarm.git

jobs:
  Poll_notebook_changes:
    runs-on: ubuntu-latest

    outputs:
      should_run: ${{ steps.poll.outputs.should_run }}
      latest_commit: ${{ steps.poll.outputs.latest_commit }}

    steps:
      - name: Poll Notebook Repository
        id: poll
        uses: devops-notebook2rest/check-notebook-changes@v0.32
        with:
          notebook_repository_url: ${{ env.NOTEBOOK_REPOSITORY_URL }}

  Build_and_deploy_N2R_API:
    needs: Poll_notebook_changes
    if: needs.Poll_notebook_changes.outputs.should_run == 'true'
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Build and deploy notebook2rest to AWS
        uses: devops-notebook2rest/notebook2rest-to-aws@v1
        with:
          aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
          eks_cluster_name: ${{ env.EKS_CLUSTER_NAME }}
          ecr_repository: ${{ env.REPOSITORY }}
          notebook_repository_name: ${{ env.NOTEBOOK_REPOSITORY_NAME }}
          notebook_repository_url: ${{ env.NOTEBOOK_REPOSITORY_URL }}
